language: generic
sudo: required
service:
    - docker

before_install:
    - docker build -t beltonp/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true beltonp/react-test npm test

after_success:
    - docker build -t beltonp/multi-client ./client
    - docker build -t beltonp/multi-nginx ./nginx
    - docker build -t beltonp/multi-server ./server
    - docker build -t beltonp/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push beltonp/multi-client
    - docker push beltonp/multi-nginx
    - docker push beltonp/multi-server
    - docker push beltonp/multi-worker
